name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build and get coverage
      run: ./gradlew build test koverReport
    
    - name: Add coverage report to PR
      id: kover
      uses: mi-kas/kover-report@v1
      with:
        path: ${{ github.workspace }}/build/reports/kover/xml/report.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 80
        min-coverage-changed-files: 80
